### ISSUE TITLE
whitelist issue

### ISSUE THREAD

**Issue by chikka** [konfer-be/typeplate#10]
When we have boolean type of value in entity whitelist ,it is returning as blank object like this {} due to sanitize method.

**Comment by konfer-be** [comment]
It is possible, this middleware is tricky. Can you give me your exact object representation ?

**Comment by chikka** [comment]
its just simple have any column with boolean value and when return it in response,it is converted in to {} object. I have fixed this using below changes  in isSanitizable method for sanitizer.service.ts file. added boolean typeof check.

`if (Util.types.isDate(value) || typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
      return false;
    }`

**Comment by konfer-be** [comment]
Nice @chikka ! I will check the bug asap and fix it in a further release.

**Comment by capital-d** [comment]
Hi, related to sinitize service, i had an issue with null object.
object.util.ts isObject return true for val = null;

**Comment by konfer-be** [comment]
Yes this is because in JS typeof null = object, so i will implements asap a more refined condition according to these remarks.

**Comment by konfer-be** [comment]
These issues are resolved in v1.4.7, thanks for your returns !
